= Softwareentwicklung im Team: Praktische Übung 9
:icons: font
:icon-set: fa
:experimental:
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:stem: latexmath
endif::[]

== Ziele der Übung

In der Übung sollen Sie Datenbankabfragen trainieren und den Umgang mit JDBC üben.

== Aufgaben

=== SQL

Für diesen Teil der Übung verwenden wir den anonymisierten AUAS Datensatz aus Woche 10. Schreiben Sie SQL Queries, die folgende Fragen beantworten:

. Welche Kurse in welchem Semester haben standardmäßig keine Einzelabgaben (Titel der Vorlesung angeben)?
. Welche Kurse gab es im Sommersemester 2015 und wer hat die Kurse gehalten?
Die Projektion soll Kurstitel sowie Nachnamen der Dozierenden enthalten.
. Wie viele Studierende mit gerader bzw. ungerader Matrikelnummer gibt es?
. Geben Sie die Verteilung der Punktzahlen für das Assignment mit der ID 228 an.
Die Ergebnistabelle soll die Punktzahl und die Häufigkeit absteigend nach der Punktzahl sortiert anzeigen.
. Wie viele Punkte haben die Studierenden, die im Wintersemester 2016 an der Veranstaltung Programmierung teilgenommen haben erreicht?
Die Ergebnistabelle sollte die Matrikelnummer der Studierenden und deren Gesamtpunktzahl enthalten.

Schauen wir uns einmal folgende Query an:

[source,sql]
----
SELECT Forename, Surname, sum(Points) FROM Courses as c 
JOIN Sheets as s ON c.ID = s.Course
JOIN Submissions as sub ON s.ID = sub.Sheet 
JOIN PostMetas as pm ON sub.ID = pm.Submission
JOIN Editors as e ON sub.ID = e.Submission
JOIN Students as st ON st.ID = e.Student
WHERE c.ID = 11
AND s.ID = 75
GROUP BY st.ID
----

Was gibt die Query als Resultat zurück?

=== JDBC

Wir wollen eine Microblogging-Anwendung mit dem Namen `Krächz` schreiben.
In der Anwendung können wir eine Mitteilung mit bis zu 140 Zeichen krächzen.

Der Rahmen der Anwendung ist bereits fertiggestellt und ist lauffähig, benutzt aber im Moment noch eine einfache Liste im Speicher. Ihre Aufgabe ist nun die Anbindung der echten Datenbank. Verwenden Sie als Datenbank MariaDB. Sie können das Docker-Compose File von Blatt 10 verwenden. 

* Die Datenbank-Dependencies im `build.gradle` File sind noch auskommentiert. 
* Die Verbindung zur Datenbank (entweder per `application.properties` oder als `DataSource` fehlt noch). 
* Sie sollten eine `schema.sql` Datei anlegen und dort die Tabellendefinition aufschreiben. Im Gegensatz zum Beispiel auf Blatt 10 sollen Sie die Tabelle nicht beim Start droppen, sondern nur dann erzeugen, falls sie nicht existiert. Alternativ können Sie die Tabelle auch von Hand anlegen.
* Die Methoden in `KraechzRepository` müssen Sie ersetzen, sodass die Datenbank verwendet wird. Eine Query soll mit reinem JDBC implementiert werden, d.h. Sie sollen hier selber die Connection aufbauen und das Statement absetzen. Achten Sie auf die korrekte Freigabe der Ressourcen, auch im Fehlerfall. Für alle anderen Queries benutzen Sie bitte `JdbcTemplate` aus Spring.
* Wenn Sie noch Zeit haben, hübschen Sie das grauenvolle Design auf.

== Ablauf der Übung

. Schalten Sie *mindestens* das Mikrofon, aber besser auch die Kamera, ein
. Am Anfang gibt es eine kurze Vorstellungsrunde
. Es wird festgelegt, in welcher Reihenfolge die "Driver" Rolle übernommen wird
. Die erste Person teilt Ihren Screen und übernimmt mithilfe von `mob` die Session
. Es wird an der Problemstellung gemeinsam gearbeitet nach den Regeln des Mob Programmings
. Nach ca. der Hälfte der Zeit gibt es ein Feedback durch die Tutorin oder den Tutor
. Es wird weiter an der Problemstellung gearbeitet
. ca. 10 Minuten vor Ende der Session bekommen Sie Ihre Abschlussbewertung

NOTE: Diese praktische Übung wird für die Zulassung gewertet.
Sie müssen vorbereitet sein und einen hinreichenden Beitrag leisten.

== Verhaltensregeln

Wir erwarten von Ihnen einen respektvollen Umgang miteinander.
Es gilt grundsätzlich bei uns der https://berlincodeofconduct.org/de/[Berlin Code of Conduct].
Die TutorInnen haben die Aufgabe, die Einhaltung der Regeln zu überwachen und können bei Verstößen gegen den Verhaltenskodex Personen aus der praktischen Übung entfernen.

